### ISSUE TITLE
Add BSON support.

### ISSUE THREAD

**Issue by caeus** [uberto/kondor-json#15]
This is the most principled approach to JSON (de)serialization that exists in Kotlin, and I'd love if there were an approach to BSON (that could be used with the mongo java async library), that were based on this Library

**Comment by uberto** [comment]
Hi @caeus I'm actually working on a functional lib to access mongo using Kondor. It's still experimental but I'm looking for beta testers.

**Comment by uberto** [comment]
Added kondor-mongo
