### ISSUE TITLE
Online converter

### ISSUE THREAD

**Issue by akbarsha03** [uberto/kondor-json#7]
Can we have an online/IDE tool to generate this converter from json to object? A little automation like https://www.json2kotlin.com. Thanks

**Comment by uberto** [comment]
This is a good idea!
I'd like to implement something like that as soon as I have some spare time.
For the moment you can generate Json converter using the kondor-tools module. See how to do in the video (around 1:00:00):
https://www.youtube.com/watch?v=hIKruBc6aeg&t=3600s

**Comment by uberto** [comment]
Now you can easily generate them with ChatGPT online, see:
https://www.youtube.com/watch?v=4v0VuxZeIIY&t=513s
